# Generated by Django 3.1.6 on 2021-02-05 23:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=10)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('order', models.JSONField(editable=False)),
            ],
        ),
    ]
